FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src
COPY PingPongClient.csproj ./
RUN dotnet restore
COPY Program.cs ./
RUN dotnet publish -c Release -o /out --no-restore

FROM mcr.microsoft.com/dotnet/runtime:10.0

WORKDIR /app
COPY --from=build /out ./

ENTRYPOINT ["dotnet", "PingPongClient.dll"]
